test_that("RiskDiff returns data.frame with expected columns.", {
  y0 <- c(10, 20)
  n0 <- c(100, 200)
  y1 <- c(15, 30)
  n1 <- c(100, 200)
  out <- RiskDiff(y0, n0, y1, n1, alpha = 0.05)
  expect_s3_class(out, "data.frame")
  expect_named(out, c("Stat", "Est", "SE", "Lower", "Upper", "P"))
  expect_equal(out$Stat, "RiskDiff")
  expect_true(out$Lower <= out$Est && out$Est <= out$Upper)
  expect_true(out$P >= 0 && out$P <= 1)
})

test_that("RiskRatio returns data.frame with expected columns.", {
  y0 <- c(10, 20)
  n0 <- c(100, 200)
  y1 <- c(15, 30)
  n1 <- c(100, 200)
  out <- RiskRatio(y0, n0, y1, n1, alpha = 0.05)
  expect_s3_class(out, "data.frame")
  expect_named(out, c("Stat", "Est", "SE", "Lower", "Upper", "P"))
  expect_equal(out$Stat, "RiskRatio")
  expect_true(out$Est > 0)
  expect_true(out$Lower <= out$Est && out$Est <= out$Upper)
})

test_that("OddsRatio returns data.frame with expected columns.", {
  y0 <- c(10, 20)
  n0 <- c(100, 200)
  y1 <- c(15, 30)
  n1 <- c(100, 200)
  out <- OddsRatio(y0, n0, y1, n1, alpha = 0.05)
  expect_s3_class(out, "data.frame")
  expect_named(out, c("Stat", "Est", "SE", "Lower", "Upper", "P"))
  expect_equal(out$Stat, "OddsRatio")
  expect_true(out$Est > 0)
  expect_true(out$Lower <= out$Est && out$Est <= out$Upper)
})
